### PR TITLE
Fix storage path for storage_path()

### LINKED ISSUE #8: Missing override path for "real-time" facades
```
file_put_contents(/var/task/storage/framework/cache/facade-d6c8a1ed6fde286ae195e535517be856b15c1f39.php): failed to open stream: No such file or directory
```

### PR DESCRIPTION
**Pull request by yangm97**
Closes #8

### CODE REVIEW

**Comment by yangm97** [comment]
```
 ------ ---------------------------------------------------------------- 
  Line   BrefServiceProvider.php                                         
 ------ ---------------------------------------------------------------- 
  67     Call to an undefined method                                     
         Illuminate\Contracts\Foundation\Application::useStoragePath().  
 ------ ---------------------------------------------------------------- 
```

Mmmaybe this repo needs `nunomaduro/larastan`.

**Comment by mnapoli** [comment]
As explained in https://github.com/brefphp/laravel-bridge/issues/8#issuecomment-672683831 I chose to move the cache directory only, instead of the whole storage, to avoid surprises like:

- storing files
- storing sessions
- storing logs

in the `/tmp/storage` directory and then loosing that data.

So if https://github.com/brefphp/laravel-bridge/issues/8#issuecomment-672683831 solves the problem, I'd rather not change the whole storage directory. Does that make sense?

**Comment by yangm97** [comment]
That's a good point actually, I'm also believe things should fail fast when something is wrong. Actually, taking a closer look at laravel/framework, it does seem like real-time facades are the only thing not making use of the cache abstraction, so I opened an issue on their side: laravel/framework#33839

**Comment by yangm97** [comment]
Ok this is not enough to fix the issue, forgot to add something ensure the path exists. Oops.

**Comment by mnapoli** [comment]
Closed in favor of https://github.com/brefphp/laravel-bridge/pull/94 (we're changing the approach initially taken by this bridge).

**Pull request closed without merging**
