### PR TITLE
Update to support Laravel 8

### PR DESCRIPTION
**Pull request by daanpeer**
When updating to Laravel I got a Composer error related to `illuminate/queue` and `illuminate/support` inside the `laravel-bridge` package. This PR updates these dependencies so that Laravel 8 can be used.

### CODE REVIEW

**Comment by pmayet** [comment]
@daanpeer You must also update the composer.json in the App used for tests

**Comment by marvinosswald** [comment]
Is there anything that need to be done here before you guys can merge it?, i'd be more than happy to help with anything.

**Comment by badams** [comment]
@daanpeer @pmayet Any chance of this getting a release soon?

**Comment by marvinosswald** [comment]
@mnapoli @pmayet just tested this with laravel 8 and a fresh project, works fine - as far as i can see.

**Comment by rmundel** [comment]
Works fine here too

**Comment by mnapoli** [comment]
Thank you everyone for testing, and thanks @daanpeer for the PR!

**Pull request merged**
